######################################################################
# Automatically generated by qmake (2.01a) Sat Jun 8 12:02:56 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += cscocket.h
SOURCES += cscocket.cpp
